#!/usr/bin/env bash

# run all tests first before pushing

# $ git config core.hooksPath .git-hooks  # (in dir) to add hooks
# $ git config --unset core.hooksPath  # (in dir) to remove hooks

if command -v hatch &>/dev/null; then
    hatch run all
else
    echo 'hooks/pre-push: command "hatch" not found, skipping hatch tests'
fi
