#!/bin/sh

# run flake8 tests first before pushing

# $ git config core.hooksPath .git-hooks  # (in dir) to add hooks
# $ git config --unset core.hooksPath  # (in dir) to remove hooks

if command -v py.test &>/dev/null; then
    py.test --flake8
else
    echo 'hooks/pre-push: command "py.test" not found, skipping flake8 tests'
fi
